config/routes.rb
Rails.application.routes.draw do

  resource :contests, only: [:show]

  resources :votes, only: [:index, :create]

  root 'votes#index'

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  has_many :votes, inverse_of: :contest
  has_many :contestants, inverse_of: :contest

  scope :current, -> { find_by(current: true) }

  validates :current, uniqueness: true

  before_save :ensure_current_consistency

  accepts_nested_attributes_for :votes

  def cached_contestants
    Rails.cache.fetch([:contest, id, :contestants], expires_in: 10.minutes) do
      contestants
    end
  end
  private
  def ensure_current_consistency
    if !self.current
      self.current = nil
    end
  end
end

app/models/contestant.rb
class Contestant < ActiveRecord::Base
  has_many :votes, inverse_of: :contestant
  belongs_to :contest, inverse_of: :contestants
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  include Humanizer
  require_human_on :create, unless: :bypass_humanizer

  attr_accessor :bypass_humanizer

  belongs_to :contestant, inverse_of: :votes
  belongs_to :contest, inverse_of: :votes

  validates :session, :contest, :contestant, presence: true
  validates :contestant, inclusion: { in: -> (vote) { vote.contest.contestants } }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  respond_to :html
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  def show
    @contest = Contest.current
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
    @contestants = contest.cached_contestants
    @vote = Vote.new
  end

  def create
    puts "nao deveria ter passado"
    @vote = contest.votes.create(resource_params)
    unless @vote.valid?
      flash[:danger] = 'Seu voto não pôde ser computado.'
    end
    @partial_result = partial_result
    respond_with(@vote)
  end

  private
  def resource_params
    params.require(:vote)
      .permit( :contestant_id,
               :humanizer_question_id,
               :humanizer_answer)
      .merge(session: request.session_options[:id])
  end

  def contest
    @contest ||= Rails.cache.fetch([:current, :contest], expires_in: 1.hour) do
      Contest.current
    end
  end

  def partial_result
    contestants = contest.cached_contestants
    {
      contestant_votes: contestants.map do |contestant|
        contestant.attributes.merge(votes: contestant.votes.count)
      end,
      total_votes: contest.votes.count
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/contests/show.html.erb
<h1><i class="sprite wall"></i> Acompanhamento do Paredão</h1>
Data limite para votos: <%= @contest.date %>

Total de votos: <%= @contest.votes.count %>

<div class="row">
  <% @contest.contestants.each do |contestant| %>
    <div class="contestant">
      <i class="sprite participant<%= contestant.id %> portrait"></i>
      <div>
        Nome: <%= contestant.name %>
      </div>
      <div>
        Qtd Votos: <%= contestant.votes.count %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Globocom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield(:body_class) %> container">
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, class: "alert alert-#{name}" do %>
      <span><%= msg %></span>
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    <% end %>
  <% end -%>

<%= yield %>

</body>
</html>

app/views/votes/_title.html.erb
<h1><i class="sprite wall"></i>QUEM DEVE SER ELIMINADO?</h1>

app/views/votes/create.html.erb
<% content_for :body_class, 'vote result' %>

<%= render 'title' %>
<h3>Parabéns! Seu voto para <%= @vote.contestant.name %> foi enviado com sucesso.</h3>
<h4>Acompanhe o resultado parcial:</h4>
<canvas id="partial_result" width="300" height="300" data-partial-result="<%= @partial_result.to_json %>"></canvas>
<%= link_to 'Votar novamente', votes_path, class: 'btn btn-info' %>

app/views/votes/index.html.erb
<% content_for :body_class, 'vote' %>

<%= render 'title' %>
<%= form_for @vote, url: {action: 'create'} do |f| %>
  <% cache "contestants_choices", expires_in: 10.minutes do %>
  <div class="row">
  <%= f.collection_radio_buttons :contestant_id, @contestants, :id, :name do |b| %>
    <label for="vote_contestant_id_<%= b.value %>" class="participant col-md-4">
      <h3 class="title"><%= b.text %></h3>
      <%= b.radio_button %>
      <div class="sprite participant<%= b.value %>"></div>
      <div>Para eliminar o <span class="bold"><%= b.text %></span> pelo telefone, disque para <span class="bold">0800-123-00<%= b.value %></span> ou mande SMS para <span class="bold">300<%= b.value %></span></div>

    </label>
  <% end %>
  </div>
  <% end %>

  <div class="col-md-8">
    <div class="humanizer center-block">
      <%= f.label :humanizer_answer, @vote.humanizer_question %>
      <%= f.text_field :humanizer_answer %>
      <%= f.hidden_field :humanizer_question_id %>
    </div>
    <%= f.submit 'Envie seu voto agora', class: 'btn btn-info center-block' %>
  </div>
<% end %>